apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kir-prod
  name: sprint-review-backend
  labels:
    app: sprint-review-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprint-review-backend
  template:
    metadata:
      namespace: kir-prod
      labels:
        app: sprint-review-backend
    spec:
      containers:
        - name: backend
          image: harbor.sch.bme.hu/org-kir-dev/sprint-review-app-v2-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 50Mi
            limits:
              cpu: 150m
              memory: 192Mi
              ephemeral-storage: 50Mi
          env:
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sprint-review-backend-secrets
                  key: DATABASE_URL
            - name: AUTHSCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sprint-review-backend-secrets
                  key: AUTHSCH_CLIENT_ID
            - name: AUTHSCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sprint-review-backend-secrets
                  key: AUTHSCH_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sprint-review-backend-secrets
                  key: JWT_SECRET
            - name: FRONTEND_URL
              value: "https://sprint-review.kir-dev.hu"
            - name: BACKEND_PUBLIC_URL
              value: "https://api.sprint-review.kir-dev.hu"
      imagePullSecrets:
        - name: harbor-secret
