apiVersion: v1
kind: Secret
metadata:
  namespace: kir-prod
  name: sprint-review-backend-secrets
  labels:
    app: sprint-review-backend
    app.kubernetes.io/name: sprint-review-backend-secrets
type: Opaque
#stringData:
#  DATABASE_URL:
#  AUTHSCH_CLIENT_ID:
#  AUTHSCH_CLIENT_SECRET:
#  JWT_SECRET:
