apiVersion: v1
kind: Secret
metadata:
  namespace: kir-prod
  name: sprint-review-backend-secrets
  labels:
    app: sprint-review-backend
    app.kubernetes.io/name: sprint-review-backend-secrets
type: Opaque
#stringData:
