apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: kir-prod
  labels:
    app: sprint-review-backend
    sprint-review-app-postgres-postgresql-client: "true"
  name: sprint-review-postgres-backup-cron-job
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sprint-review-backup
              image: harbor.sch.bme.hu/org-kir-dev/postgres-backup:latest
              imagePullPolicy: Always
              env:
                - name: PGUSER
                - name: PGPASSWORD
                - name: DBNAME
                - name: PGHOST
                - name: PGPORT
                - name: DRIVE_FILE_NAME
                - name: GOOGLE_SERVICE_ACCOUNT_KEY
                - name: WAIT_TIMEOUT_SECONDS
                - name: DRIVE_PARENT_ID
                - name: DRIVE_ID
          restartPolicy: Never
